a = 9
b = 2
ans = a + b
print(a,"+",b,"=",ans)
ans = a - b
print(a,"-",b,"=",ans)
ans = a * b
print(a,"*",b,"=",ans)
ans = a / b
print(a,"/",b,"=",ans)
ans = a // b
print(a,"//",b,"=",ans)
ans = a % b#餘數
print(a,"%",b,"=",ans)
